### ISSUE TITLE
../src/fonttools.cc:3:27: fatal error: Python/Python.h: No such file or directory

### ISSUE THREAD

**Issue by lucasbraum** [dfrankland/node-fonttools#5]
I am trying to use this npm module on a ubuntu based docker image but I am getting the following error when run npm install:

> fonttools@1.0.7 install /pipeline/source/node_modules/fonttools
> node-gyp rebuild
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.5.0
> gyp info using node@7.10.1 | linux | x64
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/pipeline/source/node_modules/fonttools/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/root/.node-gyp/7.10.1/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/7.10.1',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/pipeline/source/node_modules/fonttools',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/pipeline/source/node_modules/fonttools/build'
  CXX(target) Release/obj.target/fonttools/src/fonttools.o
../src/fonttools.cc:3:27: fatal error: Python/Python.h: No such file or directory
 #include <Python/Python.h>
                           ^
compilation terminated.
fonttools.target.mk:92: recipe for target 'Release/obj.target/fonttools/src/fonttools.o' failed
make: Leaving directory '/pipeline/source/node_modules/fonttools/build'
make: *** [Release/obj.target/fonttools/src/fonttools.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.11-coreos-r2
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /pipeline/source/node_modules/fonttools
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm info lifecycle fonttools@1.0.7~install: Failed to exec install script
npm ERR! Linux 4.8.11-coreos-r2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

> npm ERR! fonttools@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fonttools@1.0.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fonttools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fonttools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fonttools
npm ERR! There is likely additional logging output above.
  

I have run `apt-get install -y python2.7-dev` as well as other dependencies like make, gcc, g++, build-essential but I am still getting this error.

I checked and I have a Python.h file located under `./usr/include/python2.7/Python.h`.

When running npm install locally on my Mac it is working fine.

Any suggestions?

Thanks,
Lucas

**Comment by dfrankland** [comment]
Hello! I think that the [`fonttools.cc`](https://github.com/dfrankland/node-fonttools/blob/master/src/fonttools.cc) file would need to include from `python2.7` like so:

```c++
#include <python2.7/Python.h>
```

It would be even better to put these behind some guards so that it works across different OSs:

```c++
#ifdef __linux__
  #include <python2.7/Python.h>
#elif __APPLE__
  #include <Python/Python.h>
#elif __WINDOWS__
  #include <Python.h>
#else
  #error Operating system not supported
#endif
```

What do you think? Would you mind trying to see if that works? Thanks!

**Comment by lucasbraum** [comment]
That did the trick!

npm install is working fine now but I am getting an error when starting the server: 
`node: symbol lookup error: /srv/api/node_modules/fonttools-test/build/Release/fonttools.node: undefined symbol: Py_Initialize`

Maybe it is some dependency missing in my container. Trying to figure it out.

**Comment by lucasbraum** [comment]
I could fix the undefined symbol error by changing the .gyp file to include python library for linux compilations as well:

`[
                    'OS=="linux"',
                    {
                        'link_settings': {
                            'libraries': [
                                '/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so'
                            ],
                            'library_dirs': [
                              '/usr/lib',
                              '/usr/include/python2.7'
                            ]
                        }
                    }
                ]`
